In [2]:
import pandas as pd
import requests

In [5]:
response=requests.get('https://newsapi.org/v2/everything?q=tesla&from=2026-05-29&sortBy=publishedAt&apiKey=6061fb2e055f471b91ffe52f5063b488')

In [9]:
response.json()['articles']

[{'source': {'id': None, 'name': 'Pypi.org'},
  'author': None,
  'title': 'pyeasyequities added to PyPI',
  'description': 'Unofficial Easy Equities and Satrix Python Client',
  'url': 'https://pypi.org/project/pyeasyequities/',
  'urlToImage': 'https://pypi.org/static/images/twitter.abaf4b19.webp',
  'publishedAt': '2026-06-28T05:55:29Z',
  'content': 'Unofficial Python client for Easy Equities and Satrix. Intended for personal use.\r\nSupports Python 3.8+.\r\nPyPI\r\nInstallation\r\npip install pyeasyequities\r\nFeatures\r\nAccounts\r\n<ul><li>List accounts: cl… [+4867 chars]'},
 {'source': {'id': None, 'name': 'Github.com'},
  'author': 'darndt',
  'title': 'ripienaar/free-for-dev: A list of SaaS, PaaS and IaaS offerings that have free tiers of interest to devops and infradev',
  'description': 'A list of SaaS, PaaS and IaaS offerings that have free tiers of interest to devops and infradev - ripienaar/free-for-dev',
  'url': 'https://github.com/ripienaar/free-for-dev#major-cloud-providers',
  'urlToImage': 'https://opengraph.githubassets.com/45646f605dc6e9f681cffa961bb660b1e882f3dc085d30f4e07fdbc97a79cd90/ripienaar/free-for-dev',
  'publishedAt': '2026-06-28T05:47:01Z',
  'content': 'Developers and Open Source authors now have many services offering free tiers, but finding them all takes time to make informed decisions.\r\nThis is a list of software (SaaS, PaaS, IaaS, etc.) and oth… [+199222 chars]'},
 {'source': {'id': 'hacker-news', 'name': 'Hacker News'},
  'author': 'cwilkes',
  'title': "The Doorman's Fallacy in action | Hacker News",
  'description': None,
  'url': 'https://news.ycombinator.com/item?id=48678495',
  'urlToImage': None,
  'publishedAt': '2026-06-28T05:47:01Z',
  'content': 'You make some good points but some are, excuse me, cringey-wrong.&gt; physical menus are hard to update\r\nHow often does a restaurant update a menu? Those that need to update frequently already solved… [+3056 chars]'},
 {'source': {'id': None, 'name': 'Biztoc.com'},
  'author': 'notateslaapp.com',
  'title': 'Tesla Releases Q2 2026 Analyst Delivery Consensus',
  'description': 'Tesla has released its official delivery consensus again for Q2 2026. Tesla’s Investor Relations team gathers the 21 analyst delivery estimates and builds a consensus to present to investors ahead of the actual numbers, which will be published next week.\nThe …',
  'url': 'https://biztoc.com/x/9abf0468fa950679',
  'urlToImage': 'https://biztoc.com/cdn/9abf0468fa950679_s.webp',
  'publishedAt': '2026-06-28T05:20:45Z',
  'content': 'Tesla has released its official delivery consensus again for Q2 2026. Teslas Investor Relations team gathers the 21 analyst delivery estimates and builds a consensus to present to investors ahead of … [+156 chars]'},
 {'source': {'id': None, 'name': 'Korrespondent.net'},
  'author': '1',
  'title': 'Війна на Близькому Сході. Онлайн',
  'description': "США та Ізраїль проводять масштабну операцію проти Ірану. Тегеран у відповідь атакує військові об'єкти США майже у всіх країнах Перської затоки.",
  'url': 'https://ua.korrespondent.net/world/4858866/',
  'urlToImage': None,
  'publishedAt': '2026-06-28T05:15:00Z',
  'content': '. \' .\r\n 28 2026 \' . () ().\xa0 .\xa0\r\n. . " " .\r\n : \r\n28 \xa0\r\n5.34 \' . CNN, Press TV.\r\n4.35 " " \xa0 Truth Social .\r\n1.47 . (CENTCOM) .\r\nC CENTCOM 27 .\r\n27 \r\n21.15 . \xa0\xa0Reuters. , " ", , .\r\n19.10 , . , Bloomberg… [+45502 chars]'},
 {'source': {'id': None, 'name': 'Novinky.cz'},
  'author': 'Monika Kuncová',
  'title': 'Po stopách Marie Curie v\xa0jáchymovském podzemí',
  'description': 'Psal se červen 1925\xa0a\xa0Jáchymovem procházela důstojná dáma v\xa0dlouhém černém kabátu, sahajícím až ke kotníkům. Do očí jí nebylo vidět přes tmavý klobouk a\xa0brýle s\xa0kulatými obroučkami. Jen výrazná linie lícních kostí a\xa0rozhodná ústa prozrazovaly, že město navští…',
  'url': 'https://www.novinky.cz/clanek/historie-po-stopach-marie-curie-v-jachymovskem-podzemi-40584104',
  'urlToImage': 'https://d15-a.sdn.cz/d_15/c_img_qC_A/nO2CysqjGrCP7qOQhGHB0uHq/347c/marie-curie.jpeg?fl=cro,0,0,1280,720%7Cres,1200,,1%7Cwebp,75',
  'publishedAt': '2026-06-28T05:04:00Z',
  'content': 'Pro práv Jáchymov? Z\xa0odpadu tamní továrny na výrobu uranových barev izolovala spolu s\xa0manelem Pierrem v\xa0roce 1898\xa0dva do té doby neznámé radioaktivní prvky: polonium a\xa0radium. V\xa0malé kln uprosted Paí… [+11467 chars]'},
 {'source': {'id': None, 'name': 'Ixbt.com'},
  'author': 'Jin',
  'title': 'Выкупить автопилот Tesla больше не получится: систему Full Self-Driving переводят на модель подписки по всему миру',
  'description': 'С 30 июня',
  'url': 'https://www.ixbt.com/news/2026/06/28/tesla-full-self-driving.html',
  'urlToImage': 'https://media.ixbt.site/1600x900/smart/https://www.ixbt.com/img/n1/news/2026/5/0/image%20-%202026-06-28T080344.419_large.jpg',
  'publishedAt': '2026-06-28T04:56:00Z',
  'content': 'Tesla (FSD), . \r\n , , FSD 30 , .\r\n 54 000 ( 6700 ), 55 700 ( 6900 ) 222 000 ( 6900 ) .\r\n , Tesla Full Self-Driving (FSD) 14 , . , (FSD) , Tesla . 99 ( 99 ) .\r\nTesla Full Self-Driving (FSD) Tesla , , … [+16 chars]'},
 {'source': {'id': None, 'name': '3dnews.ru'},
  'author': None,
  'title': 'Apple и SpaceX получат возможность протестировать технологию Intel 14A этой осенью',
  'description': 'Вскоре после заключения соглашения о сотрудничестве с Intel, возглавляющий SpaceX и Tesla Илон Маск (Elon Musk) заявил, что будущее совместное предприятие Terafab как раз будет использовать перспективную технологию Intel 14A для выпуска чипов. Как стало извес…',
  'url': 'https://3dnews.ru/1144245/apple-i-spacex-poluchat-vozmognost-protestirovat-tehnologiyu-intel-14a-etoy-osenyu',
  'urlToImage': 'https://cdn.3dnews.ru/assets/external/illustrations/2026/06/28/1144245/14A_01.jpg',
  'publishedAt': '2026-06-28T04:48:00Z',
  'content': 'Intel, SpaceX Tesla (Elon Musk) , Terafab Intel 14A . The New York Times, SpaceX, Apple.\r\n: ASML\r\n, Intel Nvidia, $5 , SpaceX Tesla. Intel Google Apple , The New York Times , Intel Apple , , Apple .\r… [+189 chars]'},
 {'source': {'id': None, 'name': 'Biztoc.com'},
  'author': 'electrek.co',
  'title': 'Q2 2026 delivery consensus: 406,000 vehicles expected',
  'description': 'Tesla released its company-compiled delivery consensus for the second quarter of 2026, and Wall Street analysts now expect the automaker to deliver 406,024 vehicles.\nThat would be just 5.7% growth over the 384,122 vehicles Tesla delivered in Q2 2025 — a modes…',
  'url': 'https://biztoc.com/x/f2e9a6288a6c48d7',
  'urlToImage': 'https://biztoc.com/cdn/f2e9a6288a6c48d7_s.webp',
  'publishedAt': '2026-06-28T04:35:20Z',
  'content': 'Tesla released its company-compiled delivery consensus for the second quarter of 2026, and Wall Street analysts now expect the automaker to deliver 406,024 vehicles.That would be just 5.7% growth ove… [+150 chars]'},
 {'source': {'id': None, 'name': 'Onliner.by'},
  'author': 'Onliner',
  'title': 'Изгой-заучка, выскочка или гений? Начало истории Илона Маска, «придумавшего» SpaceX и Tesla\xa0(Истории)',
  'description': 'Илон Маск — выскочка. Илон Маск — гений. Илон Маск — просто талантливый менеджер. У кого-то он вызывает зависть, другие хотят походить на него. Все как обычно, когда речь идет об известном и успешном человеке. Мало кто помнит, где истоки, в чем правда, а в че…',
  'url': 'https://tech.onliner.by/2026/06/28/elon-musk-4',
  'urlToImage': 'https://content.onliner.by/news/1400x5616/8da7f81b4992b3c13a98ab9489b62481.jpeg',
  'publishedAt': '2026-06-28T04:00:20Z',
  'content': '. . . - , . , . , , , : , 1990- 2000-, - . , , « ».\r\n, 28 1971 . 55, . \xa0 , , -. , , 1979 .\r\n 2015 , , Fortune. - , , . « -», . , .\r\n, , . . , , , , , , -. , , , . , .\r\n 910 Commodore VIC-20 , . . 12 … [+2358 chars]'},
 {'source': {'id': None, 'name': 'Www.nzz.ch'},
  'author': 'Moritz Kaufmann',
  'title': 'Historische Abbaupläne bei VW: Oliver Blume ist der radikalste Manager Europas',
  'description': 'Der frühere Porsche-Manager will bei VW 100\u2005000 Stellen streichen. Er bringt eine ganze Nation gegen sich auf.',
  'url': 'https://www.nzz.ch/wirtschaft/historische-abbauplaene-bei-vw-oliver-blume-ist-der-radikalste-manager-europas-ld.10012743',
  'urlToImage': 'https://img-msp-prod.nzz.ch/2026/06/26/576efd97-5272-4e42-b4ba-37b5722c7848.jpg?width=1200&height=675&fit=bounds&quality=75&auto=webp&crop=5566,3131,x0,y543&wmark=nzz',
  'publishedAt': '2026-06-28T03:30:00Z',
  'content': 'Der frühere Porsche-Manager will bei VW 100000 Stellen streichen. Er bringt eine ganze Nation gegen sich auf.\r\nZusammenfassung\r\nUnter Druck: Der VW-Chef Oliver Blume.\r\nMalte Ossowski / Sven Simon / I… [+2286 chars]'},
 {'source': {'id': None, 'name': 'Biztoc.com'},
  'author': 'finance.yahoo.com',
  'title': 'Tesla Completes Key AI Chip Milestone in Its Push Beyond the Auto Industry',
  'description': "Tesla (NASDAQ: TSLA) and Elon Musk are making a big push to expand beyond electric vehicles (EVs). The company recently completed a tape-out for its upcoming AI5 computer chip, which will be deployed in new projects such as the Optimus humanoid robot.\nHere's …",
  'url': 'https://biztoc.com/x/cc3e38d952e5e92f',
  'urlToImage': 'https://biztoc.com/cdn/cc3e38d952e5e92f_s.webp',
  'publishedAt': '2026-06-28T03:21:10Z',
  'content': 'Tesla (NASDAQ: TSLA) and Elon Musk are making a big push to expand beyond electric vehicles (EVs). The company recently completed a tape-out for its upcoming AI5 computer chip, which will be deployed… [+151 chars]'},
 {'source': {'id': None, 'name': 'Pypi.org'},
  'author': 'jason@jasonacox.com',
  'title': 'pypowerwall-server 0.3.6',
  'description': 'A high-performance FastAPI-based server for monitoring and managing Tesla Powerwall systems',
  'url': 'https://pypi.org/project/pypowerwall-server/0.3.6/',
  'urlToImage': None,
  'publishedAt': '2026-06-28T03:04:56Z',
  'content': 'A required part of this site couldnt load. This may be due to a browser\r\n extension, network issues, or browser settings. Please check your\r\n connection, disable any ad blockers, or try using a diffe… [+12 chars]'},
 {'source': {'id': 'lenta', 'name': 'Lenta'},
  'author': 'Марина Совина',
  'title': 'Раскрыта зарплата работающего на должности «болвана» миллиардера',
  'description': 'Доходы топ-менеджеров в США достигли рекордных уровней в 2025 году. Об этом свидетельствует рейтинг газеты The Wall Street Journal (WSJ)',
  'url': 'https://lenta.ru/news/2026/06/27/raskryta-zarplata-rabotayuschego-na-dolzhnosti-bolvana-milliardera/',
  'urlToImage': 'https://icdn.lenta.ru/images/2026/06/28/04/20260628042447727/share_560ca8141a32d5525b4d9e6e2186dd7e.jpg',
  'publishedAt': '2026-06-28T01:24:00Z',
  'content': '- 2025 . The Wall Street Journal (WSJ).\r\n Block 2,75 . Block Head («»). WSJ, S&amp;P 500. 8,19 .\r\nTesla. , .'},
 {'source': {'id': None, 'name': 'Ithome.com'},
  'author': None,
  'title': '特斯拉 Model S 签名典藏版登陆欧洲：限量 20 台，仅限受邀客户购买',
  'description': 'IT之家 6 月 28 日消息，有消息称，特斯拉已私下联系欧洲部分精选客户，向其发出专属购车邀约，可入手 Model S 签名典藏版（Model S Signature Edition），收藏这款汽车史上的绝版藏品。此事经由 Facebook 德国特斯拉车友社群成员克里斯蒂安 · 达拉波扎爆料传开，他晒出了当地销售顾问发来的购车邀约详情。特斯拉资讯媒体 Drive Tesla 报道，这批典藏版车型不会上架线上公开选配页面，全部采用人工专属分配模式，由销售顾问一对一对接名额，原因是现车库存极其稀缺。特斯拉数月前已正…',
  'url': 'https://www.ithome.com/0/969/539.htm',
  'urlToImage': None,
  'publishedAt': '2026-06-28T00:27:18Z',
  'content': 'IT 6 28 Model S Model S Signature Edition\r\nFacebook · Drive Tesla \r\nModel S Model X Model SModel X \r\n 250 Model S100 Model X Model S Model X \r\n Model SModel X Plaid Model S 250 · X Model X 100 · X \r\n… [+50 chars]'},
 {'source': {'id': None, 'name': 'Khabarhub.com'},
  'author': 'Keun Lee',
  'title': 'Development in a Time of Disruption',
  'description': 'Development was once understood as a simple matter of applying the models developed economies created. But, as\xa0my research\xa0has shown, there is a\xa0catch-up paradox: a country cannot conclusively catch up with, let alone overtake, its forerunners merely by imita…',
  'url': 'https://english.khabarhub.com/2026/28/555560/',
  'urlToImage': 'https://english.khabarhub.com/wp-content/uploads/2026/06/Khabar-Hub-Article_Keun-Lee_1200px-630X-px-Final_2026.06.26-Upload.jpg',
  'publishedAt': '2026-06-28T00:15:51Z',
  'content': 'Development was once understood as a simple matter of applying the models developed economies created. But, as\xa0my research\xa0has shown, there is a\xa0catch-up paradox: a country cannot conclusively catch … [+5923 chars]'},
 {'source': {'id': None, 'name': 'Adevarul.ro'},
  'author': 'Maria Ţaga',
  'title': '28 iunie: Ziua în care Eminescu era arestat și internat la spitalul doctorului Alexandru A. Suțu',
  'description': 'Pe 28 iunie 1914, un atentat în capitala Bosniei a declanșat lanțul de evenimente care avea să ducă la izbucnirea Primului Război Mondial. Arhiducele Franz Ferdinand a fost împușcat de un tânăr extremist sârb, în timpul unei vizite oficiale la Sarajevo.',
  'url': 'https://adevarul.ro/istoria-zilei/28-iunie-ziua-in-care-eminescu-era-arestat-si-2538172.html',
  'urlToImage': 'https://cdn.adh.reperio.news/image-e/e5338b21-32bd-48e8-994f-f32c724d8e9d/index.jpeg?p=f%3Djpeg%26w%3D1200%26h%3D630%26r%3Dcover',
  'publishedAt': '2026-06-27T23:01:25Z',
  'content': 'Pe 28 iunie 1914, un atentat în capitala Bosniei a declanat lanul de evenimente care avea s duc la izbucnirea Primului Rzboi Mondial. Arhiducele Franz Ferdinand a fost împucat de un tânr extremist sâ… [+11594 chars]'},
 {'source': {'id': 'der-tagesspiegel', 'name': 'Der Tagesspiegel'},
  'author': 'Der Tagesspiegel',
  'title': 'Kalenderblatt: Was geschah am 28. Juni?',
  'description': 'Tag für Tag gibt es Ereignisse, Anekdoten, Geburts- oder Sterbetage, an die erinnert werden soll.',
  'url': 'https://www.tagesspiegel.de/kalenderblatt-was-geschah-am-28-juni-15768558.html',
  'urlToImage': 'https://www.tagesspiegel.de/images/15768557/alternates/BASE_16_9_W1400/1782597354000/kalenderblatt.jpeg',
  'publishedAt': '2026-06-27T21:55:54Z',
  'content': 'Das aktuelle Kalenderblatt für den 28. Juni 2026\r\n Namenstag \r\nDiethild, Irenäus\r\n Historische Daten \r\n2016 - Am Atatürk-Flughafen in Istanbul sprengen sich drei Selbstmordattentäter in die Luft. Sie… [+1529 chars]'},
 {'source': {'id': None, 'name': 'STERN.de'},
  'author': 'STERN.de',
  'title': 'Kalenderblatt: Was geschah am 28. Juni?',
  'description': 'Tag für Tag gibt es Ereignisse, Anekdoten, Geburts- oder Sterbetage, an die erinnert werden soll.',
  'url': 'https://www.stern.de/panorama/kalenderblatt--was-geschah-am-28--juni--37613848.html',
  'urlToImage': 'https://image.stern.de/37613850/t/rF/v1/w1440/r1.7778/-/27--5qqicu63h3v2axs2048jpeg---d08e954e12790098.jpg',
  'publishedAt': '2026-06-27T21:55:04Z',
  'content': 'Kopiere den aktuellen Link\r\nZur Merkliste hinzufügen\r\nTag für Tag gibt es Ereignisse, Anekdoten, Geburts- oder Sterbetage, an die erinnert werden soll.\r\nDas aktuelle Kalenderblatt für den 28. Juni 20… [+1580 chars]'},
 {'source': {'id': 'die-zeit', 'name': 'Die Zeit'},
  'author': 'DIE ZEIT: News -',
  'title': 'Kalenderblatt: Was geschah am 28. Juni?',
  'description': 'Hier finden Sie Informationen zu dem Thema „Kalenderblatt“. Lesen Sie jetzt „Was geschah am 28. Juni?“.',
  'url': 'https://www.zeit.de/news/2026-06/27/was-geschah-am-28-juni',
  'urlToImage': 'https://img.zeit.de/news/2026-06/27/was-geschah-am-28-juni-image-group/wide__1300x731',
  'publishedAt': '2026-06-27T21:55:04Z',
  'content': 'Das aktuelle Kalenderblatt für den 28. Juni 2026\r\nNamenstag\r\nDiethild, Irenäus\r\nHistorische Daten\r\n2016 - Am Atatürk-Flughafen in Istanbul sprengen sich drei Selbstmordattentäter in die Luft. Sie rei… [+1479 chars]'},
 {'source': {'id': None, 'name': 'Mail.ru'},
  'author': 'Леонид Монин',
  'title': '55 Илону Маску: инженер с 14 детьми, чудак с триллионом долларов и главный слоняра в России',
  'description': '28 июня 2026 года Илону Маску исполняется 55 лет. Разбираем биографию, состояние, проекты Tesla и SpaceX и почему он так популярен в России — в материале Life.ru.',
  'url': 'https://news.mail.ru/society/71431786/',
  'urlToImage': 'https://resizer.mail.ru/p/248a9604-bb26-5733-9d23-2b7fcfe413ae/AQAGajgjGJ9_Qar_EFx7MpEfvwGmGxAloxZeNeAuEtyBsKKDY9VsdwFpDZYe8f7DuFiWz9vSODPH5y6L5ta-jLBcK8Y.jpg',
  'publishedAt': '2026-06-27T21:47:09Z',
  'content': '28\xa0 2026 55 . \xa0 \xa0— \xa0 \xa0$500 \xa0 \xa0, \xa0, \xa0 . \xa0 , \xa0, \xa0. \xa0 , - \xa0-, \xa0-\xa0 \xa0 \xa0, « ». \xa0 , , \xa0 \xa0 \xa0— \xa0 LIFE.\r\n28\xa0 1971 \xa0 (). : \xa0 \xa0 , \xa0— \xa0 \xa0 , \xa0 \xa02002 . : , \xa0.\r\n: , , \xa0\xa0, , \xa0 , \xa0 \xa0 « » \xa0 . \xa0: \xa012 Blastar \xa0 \xa0\xa0$500. .… [+1975 chars]'},
 {'source': {'id': None, 'name': 'Life.ru'},
  'author': 'https://www.facebook.com/lifenews.ru/',
  'title': '55 Илону Маску: инженер с 14 детьми, чудак с триллионом долларов и главный слоняра в России',
  'description': '28 июня 2026 года Илону Маску исполняется 55 лет. Разбираем биографию, состояние, проекты Tesla и SpaceX и почему он так популярен в России — в материале Life.ru.',
  'url': 'https://life.ru/p/1891405',
  'urlToImage': 'https://static.life.ru/ip/unsafe/rs:fit:1200:/q:98/sh:0.5/czM6Ly9saWZlLXN0YXRpYy9wdWJsaWNhdGlvbnMvMjAyNi82LzI1LzE1ODExMzMzMjc1MTMuMjU2LlBORw==.webp',
  'publishedAt': '2026-06-27T21:45:00Z',
  'content': '. 55 . © Life.ru. © / Patrick Pleul, © ChatGPT\r\n28 2026 55 . $500 , , . , , . , - -, - , « ». , , LIFE.\r\n 28 1971 (). : , , 2002 . : , .\r\n : , , , , , « » . : 12 Blastar $500. .\r\n ? . 17 , , . , (), … [+1884 chars]'},
 {'source': {'id': 'lenta', 'name': 'Lenta'},
  'author': 'Нэлли Свердлова',
  'title': '28 июня: какой праздник отмечают в России и мире',
  'description': '28 июня профессиональный праздник отмечают букмекеры, а день рождения празднует американский предприниматель Илон Маск. «Лента.ру» рассказывает, какие еще торжества приходятся на конец июня, кто из известных людей отмечает день рождения и на какие приметы 28 …',
  'url': 'https://lenta.ru/news/2026/06/28/28-iyunya-kakoy-prazdnik-segodnya-otmechayut-v-rossii-i-mire/',
  'urlToImage': 'https://icdn.lenta.ru/images/2026/06/19/09/20260619094017782/share_09b62b5fe9e5dd0d4bac93f4a994a63a.jpg',
  'publishedAt': '2026-06-27T21:05:00Z',
  'content': '28 , . «.» , , 28 .\r\n, , . . , , . .\r\n , : .\r\n oacoo 1956 \r\n" !" - 1956 . : Public domain / Wikipedia\r\n28 1956 , , « ». , . , 80 . , .\r\n 28 \r\n 28 \r\nIII -. . , , . 13 , .\r\n « » , , , «» . , , .\r\nFortu… [+306 chars]'},
 {'source': {'id': None, 'name': 'Iz.ru'},
  'author': 'Ямков Ренат Рашидович',
  'title': 'Предприниматель и основатель компании SpaceX Илон Маск. Биография',
  'description': 'Илон Маск — американский предприниматель, инженер и миллиардер, ставший в июне 2026 года первым в истории долларовым триллионером. Он является основателем компании SpaceX, генеральным директором Tesla и владельцем социальной сети X (бывший Twitter). В 2025 го…',
  'url': 'https://iz.ru/2118142/predprinimatel-i-osnovatel-kompanii-spacex-ilon-mask-biografiia-izi',
  'urlToImage': 'http://cdn.iz.ru/sites/default/files/styles/900x506/public/news-2026-06/20250120_faa_s152_091_0.jpg?itok=yiCxYjJz',
  'publishedAt': '2026-06-27T21:00:00Z',
  'content': ', , 2026 . SpaceX, Tesla X ( Twitter). 2025 , . «».\r\n28 1971 , . , , , ( ) . : 1983 , 12 , Blastar.\r\n 1989 , , . 1997 , . 2002 .\r\n. 1990- Zip2, . X.com, PayPal. eBay 2002 .\r\n -\r\n 2002 SpaceX, . . Tes… [+715 chars]'},
 {'source': {'id': None, 'name': 'Overclockers.ru'},
  'author': 'kosmos_news',
  'title': 'Продажи электромобилей Tesla в Европе внезапно выросли на 77% на фоне снижения цен',
  'description': 'Электромобили стали более конкурентоспособными по сравнению с автомобилями с двигателями внутреннего сгорания и недорогими машинами из Китая.',

In [19]:
df = pd.DataFrame(response.json()['articles'])

In [13]:
pd.DataFrame(response.json()['articles']).head(10)

,source,author,title,description,url,urlToImage,publishedAt,content
0,"{'id': None, 'name': 'Pypi.org'}",None,pyeasyequities added to PyPI,Unofficial Easy Equities and Satrix Python Client,https://pypi.org/project/pyeasyequities/,https://pypi.org/static/images/twitter.abaf4b1...,2026-06-28T05:55:29Z,Unofficial Python client for Easy Equities and...
1,"{'id': None, 'name': 'Github.com'}",darndt,"ripienaar/free-for-dev: A list of SaaS, PaaS a...","A list of SaaS, PaaS and IaaS offerings that h...",https://github.com/ripienaar/free-for-dev#majo...,https://opengraph.githubassets.com/45646f605dc...,2026-06-28T05:47:01Z,Developers and Open Source authors now have ma...
2,"{'id': 'hacker-news', 'name': 'Hacker News'}",cwilkes,The Doorman's Fallacy in action | Hacker News,None,https://news.ycombinator.com/item?id=48678495,None,2026-06-28T05:47:01Z,"You make some good points but some are, excuse..."
3,"{'id': None, 'name': 'Biztoc.com'}",notateslaapp.com,Tesla Releases Q2 2026 Analyst Delivery Consensus,Tesla has released its official delivery conse...,https://biztoc.com/x/9abf0468fa950679,https://biztoc.com/cdn/9abf0468fa950679_s.webp,2026-06-28T05:20:45Z,Tesla has released its official delivery conse...
4,"{'id': None, 'name': 'Korrespondent.net'}",1,Війна на Близькому Сході. Онлайн,США та Ізраїль проводять масштабну операцію пр...,https://ua.korrespondent.net/world/4858866/,None,2026-06-28T05:15:00Z,". ' .\r\n 28 2026 ' . () (). . \r\n. . "" "" .\..."
5,"{'id': None, 'name': 'Novinky.cz'}",Monika Kuncová,Po stopách Marie Curie v jáchymovském podzemí,Psal se červen 1925 a Jáchymovem procházela dů...,https://www.novinky.cz/clanek/historie-po-stop...,https://d15-a.sdn.cz/d_15/c_img_qC_A/nO2CysqjG...,2026-06-28T05:04:00Z,Pro práv Jáchymov? Z odpadu tamní továrny na v...
6,"{'id': None, 'name': 'Ixbt.com'}",Jin,Выкупить автопилот Tesla больше не получится: ...,С 30 июня,https://www.ixbt.com/news/2026/06/28/tesla-ful...,https://media.ixbt.site/1600x900/smart/https:/...,2026-06-28T04:56:00Z,"Tesla (FSD), . \r\n , , FSD 30 , .\r\n 54 000 ..."
7,"{'id': None, 'name': '3dnews.ru'}",None,Apple и SpaceX получат возможность протестиров...,Вскоре после заключения соглашения о сотруднич...,https://3dnews.ru/1144245/apple-i-spacex-poluc...,https://cdn.3dnews.ru/assets/external/illustra...,2026-06-28T04:48:00Z,"Intel, SpaceX Tesla (Elon Musk) , Terafab Inte..."
8,"{'id': None, 'name': 'Biztoc.com'}",electrek.co,"Q2 2026 delivery consensus: 406,000 vehicles e...",Tesla released its company-compiled delivery c...,https://biztoc.com/x/f2e9a6288a6c48d7,https://biztoc.com/cdn/f2e9a6288a6c48d7_s.webp,2026-06-28T04:35:20Z,Tesla released its company-compiled delivery c...
9,"{'id': None, 'name': 'Onliner.by'}",Onliner,"Изгой-заучка, выскочка или гений? Начало истор...",Илон Маск — выскочка. Илон Маск — гений. Илон ...,https://tech.onliner.by/2026/06/28/elon-musk-4,https://content.onliner.by/news/1400x5616/8da7...,2026-06-28T04:00:20Z,". . . - , . , . , , , : , 1990- 2000-, - . , ,..."

In [14]:
pd.DataFrame(response.json()['articles'])[['author','title','description','publishedAt']]

,author,title,description,publishedAt
0,None,pyeasyequities added to PyPI,Unofficial Easy Equities and Satrix Python Client,2026-06-28T05:55:29Z
1,darndt,"ripienaar/free-for-dev: A list of SaaS, PaaS a...","A list of SaaS, PaaS and IaaS offerings that h...",2026-06-28T05:47:01Z
2,cwilkes,The Doorman's Fallacy in action | Hacker News,None,2026-06-28T05:47:01Z
3,notateslaapp.com,Tesla Releases Q2 2026 Analyst Delivery Consensus,Tesla has released its official delivery conse...,2026-06-28T05:20:45Z
4,1,Війна на Близькому Сході. Онлайн,США та Ізраїль проводять масштабну операцію пр...,2026-06-28T05:15:00Z
...,...,...,...,...
93,Eber do Carmo,Novo Hyundai Elantra cresce e muda de cara par...,Difícil reconhecer o sedã compacto da Hyundai ...,2026-06-27T08:00:47Z
94,None,2028 hopeful fires back at Elon Musk after tri...,Rep. Ro Khanna says he won't be intimidated by...,2026-06-27T08:00:11Z
95,Shawn Tully,Big Short legend Steve Eisman says everyone is...,Eisman famously called the housing bubble. Now...,2026-06-27T08:00:00Z
96,Levent Öztürk,"Tesla için rüzgar tersine döndü, Avrupa satışl...",Elon Musk'ın siyaset sahnesindeki radikal söyl...,2026-06-27T07:41:03Z
97,Alberto Martín,Nos colaron un detalle nostálgico en Los Cuatr...,El Universo Cinematográfico Marvel se ha conve...,2026-06-27T07:00:12Z

In [21]:
df.shape

(98, 8)

In [22]:
df.to_csv('news.csv')